# Generated by Django 5.1.2 on 2024-11-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skynexusdata',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='skynexusdata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skynexusdata',
            name='temparture',
        ),
        migrations.AddField(
            model_name='skynexusdata',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='skynexusdata',
            name='feels_like',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='skynexusdata',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skynexusdata',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='skynexusdata',
            name='weather_description',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='skynexusdata',
            name='wind_speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='skynexusdata',
            name='city',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
